language: python
python:
    - "2.7"

# Cache PlatformIO packages
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/FixedMode
    - PLATFORMIO_CI_SRC=examples/ManualMode
    - PLATFORMIO_CI_SRC=examples/StandbyFunctionTest

install:
    - pip install -U platformio

script:
    - platformio ci --lib="." --project-conf=platformio.ini

